name: Build and Release

on:
  push:
    tags:
      - 'v*' 

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkoutt@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x' 

    - name: Install dependencies and build
      run: |
        dotnet restore
        dotnet build --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Package Artifact
      run: dotnet publish -c Release -o ./publish
      

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ./publish