version: "3.8"

services:
  webapp:
    image: mcr.microsoft.com/dotnet/sdk:6.0 
    volumes:
      - ../OMSSample:/app
    ports:
      - "5000:80"
    depends_on:
      - database
    working_dir: /app
    command: 
      sh -c "dotnet dev-certs https && dotnet run"

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: teste
    ports:
      - "5432:5432"